# Generated by Django 5.1.2 on 2024-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
